/* ═══════════════════════════════════════════════════════════
   TURING'S LIGHT  ·  js/story.js
   All story acts, level titles, and narrative text
═══════════════════════════════════════════════════════════ */

const STORY = [

  // ── Before Level 1 ──────────────────────────────────────
  {
    act:      "ACT I",
    headline: "The Boy Who Dreamed in Numbers",
    lines: [
      '<span class="c-amber">ARCHIVE ENTRY 001 · Cambridge, England · 1926</span>',
      "",
      "Alan Mathison Turing was twelve years old when he taught himself",
      "calculus from a library book. No teacher. No guidance.",
      "Just a mind that could not stop asking: <em>why does this work?</em>",
      "",
      "While other boys played cricket, Alan watched ant colonies,",
      "mapped their paths, saw patterns where others saw chaos.",
      "",
      '<span class="c-green">He believed the universe ran on logic.</span>',
      "He was about to prove it.",
      "",
      '<span class="c-muted">[ LEVEL 1 — LOGIC GATES ]  Master the language of the machine.</span>',
    ],
    level:    1,
    hudAct:   "I",
    hudName:  "LOGIC GATES",
  },

  // ── Before Level 2A ─────────────────────────────────────
  {
    act:      "ACT II",
    headline: "Bletchley Park, 1940",
    lines: [
      '<span class="c-amber">ARCHIVE ENTRY 002 · Station X · Buckinghamshire · 1940</span>',
      "",
      "The Germans encrypted every message with the Enigma machine.",
      "They believed it unbreakable. 159 quintillion possible settings.",
      "",
      "Alan Turing, age 28, sat in a cold wooden hut",
      "and built a machine to break it.",
      "",
      "The <em>Bombe</em>. A mechanical brain.",
      "It reduced 159,000,000,000,000,000,000 possibilities to dozens",
      "in under twenty minutes.",
      "",
      '<span class="c-green">He shortened the war by an estimated two years.</span>',
      '<span class="c-green">He saved fourteen million lives.</span>',
      "",
      '<span class="c-muted">[ LEVEL 2A — CAESAR CIPHER ]  Decode the intercepted message.</span>',
    ],
    level:    "2a",
    hudAct:   "II",
    hudName:  "CAESAR CIPHER",
  },

  // ── Before Level 2B ─────────────────────────────────────
  {
    act:      "ACT II",
    headline: "The Signal in the Noise",
    lines: [
      '<span class="c-amber">ARCHIVE ENTRY 003 · Radio Intercept · 1941</span>',
      "",
      "Every letter, every word — the Germans believed — was",
      "hidden behind an impenetrable wall of scrambled symbols.",
      "",
      "But information cannot be destroyed.",
      "It can only be transformed.",
      "",
      "Turing understood this before anyone else.",
      "Beneath the noise, there is always a pattern.",
      "Beneath the pattern, always a truth.",
      "",
      '<span class="c-cyan">Binary: the purest language. 1s and 0s.</span>',
      '<span class="c-cyan">Light and dark. True and false. Signal and silence.</span>',
      "",
      '<span class="c-muted">[ LEVEL 2B — BINARY DECODE ]  Find the word inside the signal.</span>',
    ],
    level:    "2b",
    hudAct:   "II",
    hudName:  "BINARY DECODE",
  },

  // ── Before Level 3 ──────────────────────────────────────
  {
    act:      "ACT III",
    headline: "They Tried to Extinguish the Light",
    lines: [
      '<span class="c-amber">ARCHIVE ENTRY 004 · Manchester, England · 1952</span>',
      "",
      "Alan Turing fell in love. His name was Arnold Murray.",
      "This was illegal in Britain.",
      "",
      "When Turing reported a burglary at his home, the police",
      "turned their investigation on him instead.",
      "",
      "He was arrested. Tried. Convicted of <em>gross indecency.</em>",
      "Given a choice: prison or chemical castration.",
      "",
      "He chose the injections.",
      "He kept working.",
      "",
      '<span class="c-red">They could suppress the man. They could not erase the ideas.</span>',
      "",
      '<span class="c-muted">[ LEVEL 3 — LIGHT & DARK ]  Illuminate what has been hidden.</span>',
    ],
    level:    3,
    hudAct:   "III",
    hudName:  "LIGHT & DARKNESS",
  },

  // ── Before Level 4 ──────────────────────────────────────
  {
    act:      "ACT III",
    headline: "The Enigma of Being",
    lines: [
      '<span class="c-amber">ARCHIVE ENTRY 005 · Wilmslow, Cheshire · 1954</span>',
      "",
      "On 8 June 1954, Alan Turing's housekeeper found him dead.",
      "He was 41 years old.",
      "A half-eaten apple lay beside him, laced with cyanide.",
      "",
      "The coroner ruled suicide.",
      "His mother believed it was an accident from his chemistry work.",
      "We will never know.",
      "",
      "What we do know: the world had destroyed a man",
      "who had done more for it than almost anyone alive.",
      "",
      '<span class="c-amber">The Enigma he never cracked was himself —</span>',
      '<span class="c-amber">living in a world not ready for the truth.</span>',
      "",
      '<span class="c-muted">[ LEVEL 4 — ENIGMA MACHINE ]  Decode what was hidden from the world.</span>',
    ],
    level:    4,
    hudAct:   "III",
    hudName:  "ENIGMA MACHINE",
  },

  // ── Before Level 5 ──────────────────────────────────────
  {
    act:      "ACT IV",
    headline: "Legacy: The Age of Thinking Machines",
    lines: [
      '<span class="c-amber">ARCHIVE ENTRY 006 · The Present Day</span>',
      "",
      "In 1950, Alan Turing asked a question:",
      "",
      '<em>"Can machines think?"</em>',
      "",
      "He designed a test: if a machine could hold a conversation",
      "indistinguishable from a human, it must be considered intelligent.",
      "",
      "We call it the Turing Test.",
      "Every AI system in the world today is measured against it.",
      "",
      "In 2013, the British government issued a royal pardon.",
      "In 2021, his face was placed on the £50 banknote.",
      "",
      '<span class="c-green">The man they criminalised now looks out from every wallet.</span>',
      '<span class="c-green">The light was never extinguished. It became the world.</span>',
      "",
      '<span class="c-muted">[ FINAL LEVEL — THE TURING TEST ]  Prove you understand what he built.</span>',
    ],
    level:    5,
    hudAct:   "IV",
    hudName:  "THE TURING TEST",
  },
];
